---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  vars:
    pacemaker_password: pacemaker
    molecule_test: true
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Register containers ip
      ansible.builtin.set_fact:
        container_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Register vip
      ansible.builtin.set_fact:
        vip: "{{ container_ip.split('.')[:3] | join('.') ~ '.200' }}"

    - name: Install pip
      ansible.builtin.package:
        name: "python3-pip"
        state: present

    # https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check
    - name: Install pyOpenSSL
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - pyOpenSSL

  roles:
    - {role: vrrp}
