---
- name: Verify
  hosts: all
  become: true

  tasks:
  post_tasks:

    - name: Register containers ip
      ansible.builtin.set_fact:
        container_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Register vip
      ansible.builtin.set_fact:
        vip: "{{ container_ip.split('.')[:3] | join('.') ~ '.200' }}"

    - name: Pause for 1 minutes
      ansible.builtin.pause:
        minutes: 1

    - name: Check that a page returns a status 200 and register answer
      ansible.builtin.uri:
        url: http://{{ vip }}
        return_content: yes
      register: answer

    - name: Check nginx answer return vrrp-test
      ansible.builtin.assert:
        that:
          - "'vrrp-test' in answer.content"

    - name: Save cluster status
      ansible.builtin.command: pcs status
      register: pcs_status

    - name: some debug 2
      ansible.builtin.debug:
        var: pcs_status

    - name: Check cluster is online
      ansible.builtin.assert:
        that:
          - "'Online: [ vrrp-1 vrrp-2 vrrp-3 ]' in pcs_status.stdout"
