---
- name: Install VRRP Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ vrrp_package }}"

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Customize Nginx
  ansible.builtin.shell: echo '<h1>{{ hostvars[inventory_hostname]['ansible_fqdn'] }} - vrrp-test</h1>' > /var/www/html/index.nginx-debian.html
  changed_when: false
